chores: refactor code of bin/create-merge-branch
Signed-off-by: Mathieu Grzybek <mathieu@stackhpc.com>

diff --git a/bin/create-merge-branch b/bin/create-merge-branch
--- a/bin/create-merge-branch
+++ b/bin/create-merge-branch
@@ -6,33 +6,83 @@
 
 set -e
 
+#####
+# Functions
+#####
+
+function export_latest_release_tag() {
+	local upstream_repo=$1
+
+	# Fetch the tag for the latest release from the upstream repository
+	export RELEASE_TAG="$(curl -fsSL "https://api.github.com/repos/${upstream_repo}/releases/latest" | jq -r '.tag_name')"
+	echo "[INFO] Found latest release tag - $RELEASE_TAG"
+}
+
+# Add the repository as an upstream
+function add_upstream_remote() {
+	local upstream_repo=$1
+
+	echo "[INFO] Adding upstream remote..."
+	git remote add upstream "https://github.com/${upstream_repo}.git"
+	git remote show upstream
+
+	echo "[INFO] Fetching remote tags..."
+	git remote update
+}
+
+function merge_release_tag() {
+	local release_tag=$1
+
+	echo "[INFO] Merging release tag - $release_tag"
+	echo "[INFO] Release tag commit - $(git rev-parse "$release_tag")"
+
+	git merge --strategy recursive -X theirs --no-commit "$release_tag"
+}
+
+function checkout_commmit_push() {
+	local branch_name=$1
+	local default_branch=$2
+	local release_tag=$3
+
+	echo "[INFO] Checking out temporary branch '$branch_name'..."
+	git checkout -b "$branch_name"
+
+	echo "[INFO] Committing changes"
+	git commit -m "Upgrade Azimuth to $release_tag"
+
+	echo "[INFO] Pushing changes to origin"
+	git push --set-upstream origin "$branch_name"
+
+	# Go back to the default branch at the end
+	echo "[INFO] Reverting back to $default_branch"
+	git checkout "$default_branch"
+
+	echo "[INFO] Removing temporary branch"
+	git branch -d "$branch_name"
+}
+
+#####
+# Business logic
+#####
+
 # Only allow running on main
 CURRENT_BRANCH="$(git branch --show-current)"
 DEFAULT_BRANCH="${DEFAULT_BRANCH:-"main"}"
 if [ "$CURRENT_BRANCH" != "$DEFAULT_BRANCH" ]; then
-  echo "[ERROR] This script can only be run on the $DEFAULT_BRANCH branch" >&2
-  exit 1
+	echo "[ERROR] This script can only be run on the $DEFAULT_BRANCH branch" >&2
+	exit 1
 fi
 
 if [ -n "$(git status --short)" ]; then
-  echo "[ERROR] This script cannot run with uncommitted changes" >&2
-  exit 1
+	echo "[ERROR] This script cannot run with uncommitted changes" >&2
+	exit 1
 fi
 
 UPSTREAM_REPO="${UPSTREAM_REPO:-"azimuth-cloud/azimuth-config"}"
 echo "[INFO] Using upstream repo - $UPSTREAM_REPO"
 
-# Fetch the tag for the latest release from the upstream repository
-RELEASE_TAG="$(curl -fsSL "https://api.github.com/repos/${UPSTREAM_REPO}/releases/latest" | jq -r '.tag_name')"
-echo "[INFO] Found latest release tag - $RELEASE_TAG"
-
-# Add the repository as an upstream
-echo "[INFO] Adding upstream remote..."
-git remote add upstream "https://github.com/${UPSTREAM_REPO}.git"
-git remote show upstream
-
-echo "[INFO] Fetching remote tags..."
-git remote update
+export_latest_release_tag $UPSTREAM_REPO
+add_upstream_remote $UPSTREAM_REPO
 
 # Use a branch that is named for the release
 BRANCH_NAME="upgrade/$RELEASE_TAG"
@@ -40,44 +90,28 @@ BRANCH_NAME="upgrade/$RELEASE_TAG"
 # Check if the branch already exists on the origin
 # If it does, there is nothing more to do as the branch can be rebased from the MR
 if git show-branch "remotes/origin/$BRANCH_NAME" >/dev/null 2>&1; then
-  echo "[INFO] Merge branch already created for $RELEASE_TAG"
-  exit
+	echo "[INFO] Merge branch already created for $RELEASE_TAG"
+	exit
 fi
 
-echo "[INFO] Merging release tag - $RELEASE_TAG"
-echo "[INFO] Release tag commit - $(git rev-parse "$RELEASE_TAG")"
-git merge --strategy recursive -X theirs --no-commit "$RELEASE_TAG"
+merge_release_tag $RELEASE_TAG
 
 # Check if the merge resulted in any changes being staged
 if [ -n "$(git status --short)" ]; then
-  echo "[INFO] Merge resulted in the following changes"
-  git status
+	echo "[INFO] Merge resulted in the following changes"
+	git status
 
-  # NOTE(scott): The GitHub create-pull-request action does
-  # the committing for us, so we only need to make branches
-  # and commits if running outside of GitHub actions.
-  if [ ! "$GITHUB_ACTIONS" ]; then
-    echo "[INFO] Checking out temporary branch '$BRANCH_NAME'..."
-    git checkout -b "$BRANCH_NAME"
+	# NOTE(scott): The GitHub create-pull-request action does
+	# the committing for us, so we only need to make branches
+	# and commits if running outside of GitHub actions.
+	if [ ! "$GITHUB_ACTIONS" ]; then
+		checkout_commmit_push $BRANCH_NAME $DEFAULT_BRANCH $RELEASE_TAG
+	fi
 
-    echo "[INFO] Committing changes"
-    git commit -m "Upgrade Azimuth to $RELEASE_TAG"
-
-    echo "[INFO] Pushing changes to origin"
-    git push --set-upstream origin "$BRANCH_NAME"
-
-    # Go back to the default branch at the end
-    echo "[INFO] Reverting back to $DEFAULT_BRANCH"
-    git checkout "$DEFAULT_BRANCH"
-
-    echo "[INFO] Removing temporary branch"
-    git branch -d "$BRANCH_NAME"
-  fi
-
-  # Write a file containing the branch name and tag
-  # for automatic PR or MR creation that follows
-  echo "BRANCH_NAME=\"$BRANCH_NAME\"" >.mergeenv
-  echo "RELEASE_TAG=\"$RELEASE_TAG\"" >>.mergeenv
+	# Write a file containing the branch name and tag
+	# for automatic PR or MR creation that follows
+	echo "BRANCH_NAME=\"$BRANCH_NAME\"" >.mergeenv
+	echo "RELEASE_TAG=\"$RELEASE_TAG\"" >>.mergeenv
 else
-  echo "[INFO] Merge resulted in no changes"
+	echo "[INFO] Merge resulted in no changes"
 fi
