fix: linting
Signed-off-by: Mathieu Grzybek <mathieu@stackhpc.com>

diff --git a/bin/create-merge-branch b/bin/create-merge-branch
--- a/bin/create-merge-branch
+++ b/bin/create-merge-branch
@@ -10,68 +10,71 @@ set -e
 # Functions
 #####
 
-function export_latest_release_tag() {
-	local upstream_repo=$1
+function get_latest_release_tag() {
+  local upstream_repo=$1
+  local release_tag
 
-	# Fetch the tag for the latest release from the upstream repository
-	export RELEASE_TAG="$(curl -fsSL "https://api.github.com/repos/${upstream_repo}/releases/latest" | jq -r '.tag_name')"
-	echo "[INFO] Found latest release tag - $RELEASE_TAG"
+  # Fetch the tag for the latest release from the upstream repository
+  release_tag="$(curl -fsSL "https://api.github.com/repos/${upstream_repo}/releases/latest" | jq -r '.tag_name')"
+  echo "[INFO] Found latest release tag - $release_tag"
+
+  return "$release_tag"
 }
 
 function verify_release_tag() {
-	local upstream_repo=$1
-	local release_tag=$2
+  local upstream_repo=$1
+  local release_tag=$2
 
-	if curl -fsSL "https://api.github.com/repos/${upstream_repo}/releases" | jq -r '.[].tag_name' | fgrep $release_tag; then
-		echo "[INFO] The provided tag $release_tag exists in the upstream repository"
-		return
-	fi
+  if curl -fsSL "https://api.github.com/repos/${upstream_repo}/releases" | jq -r '.[].tag_name' | grep -F "$release_tag"; then
+    echo "[INFO] The provided tag $release_tag exists in the upstream repository"
+    return
+  fi
 
-	echo "[ERROR] The provided tag $release_tag does not exist in the upstream repository"
-	exit 1
+  echo "[ERROR] The provided tag $release_tag does not exist in the upstream repository"
+  exit 1
 }
 
 # Add the repository as an upstream
 function add_upstream_remote() {
-	local upstream_repo=$1
+  local upstream_repo=$1
 
-	echo "[INFO] Adding upstream remote..."
-	git remote add upstream "https://github.com/${upstream_repo}.git"
-	git remote show upstream
+  echo "[INFO] Adding upstream remote..."
+  git remote add upstream "https://github.com/${upstream_repo}.git"
+  git remote show upstream
 
-	echo "[INFO] Fetching remote tags..."
-	git remote update
+  echo "[INFO] Fetching remote tags..."
+  git remote update
 }
 
 function merge_release_tag() {
-	local release_tag=$1
+  local release_tag=$1
 
-	echo "[INFO] Merging release tag - $release_tag"
-	echo "[INFO] Release tag commit - $(git rev-parse "$release_tag")"
+  echo "[INFO] Merging release tag - $release_tag"
+  echo "[INFO] Release tag commit - $(git rev-parse "$release_tag")"
 
-	git merge --strategy recursive -X theirs --no-commit "$release_tag"
+  git merge --strategy recursive -X theirs --no-commit "$release_tag"
 }
 
 function checkout_commmit_push() {
-	local branch_name=$1
-	local default_branch=$2
-	local release_tag=$3
+  local branch_name=$1
+  local default_branch=$2
+  local release_tag=$3
 
-	echo "[INFO] Checking out temporary branch '$branch_name'..."
-	git checkout -b "$branch_name"
+  echo "[INFO] Checking out temporary branch '$branch_name'..."
+  git checkout -b "$branch_name"
 
-	echo "[INFO] Committing changes"
-	git commit -m "Upgrade Azimuth to $release_tag"
+  echo "[INFO] Committing changes"
+  git commit -m "Upgrade Azimuth to $release_tag"
 
-	echo "[INFO] Pushing changes to origin"
-	git push --set-upstream origin "$branch_name"
+  echo "[INFO] Pushing changes to origin"
+  git push --set-upstream origin "$branch_name"
 
-	# Go back to the default branch at the end
-	echo "[INFO] Reverting back to $default_branch"
-	git checkout "$default_branch"
+  # Go back to the default branch at the end
+  echo "[INFO] Reverting back to $default_branch"
+  git checkout "$default_branch"
 
-	echo "[INFO] Removing temporary branch"
-	git branch -d "$branch_name"
+  echo "[INFO] Removing temporary branch"
+  git branch -d "$branch_name"
 }
 
 #####
@@ -82,13 +85,13 @@ function checkout_commmit_push() {
 CURRENT_BRANCH="$(git branch --show-current)"
 DEFAULT_BRANCH="${DEFAULT_BRANCH:-"main"}"
 if [ "$CURRENT_BRANCH" != "$DEFAULT_BRANCH" ]; then
-	echo "[ERROR] This script can only be run on the $DEFAULT_BRANCH branch" >&2
-	exit 1
+  echo "[ERROR] This script can only be run on the $DEFAULT_BRANCH branch" >&2
+  exit 1
 fi
 
 if [ -n "$(git status --short)" ]; then
-	echo "[ERROR] This script cannot run with uncommitted changes" >&2
-	exit 1
+  echo "[ERROR] This script cannot run with uncommitted changes" >&2
+  exit 1
 fi
 
 UPSTREAM_REPO="${UPSTREAM_REPO:-"azimuth-cloud/azimuth-config"}"
@@ -97,11 +100,11 @@ echo "[INFO] Using upstream repo - $UPSTREAM_REPO"
 RELEASE_TAG="${RELEASE_TAG:-}"
 
 if [ -z "$RELEASE_TAG" ]; then
-	export_latest_release_tag $UPSTREAM_REPO
+  RELEASE_TAG=$(get_latest_release_tag "$UPSTREAM_REPO")
 else
-	verify_release_tag $UPSTREAM_REPO $RELEASE_TAG
+  verify_release_tag "$UPSTREAM_REPO" "$RELEASE_TAG"
 fi
-add_upstream_remote $UPSTREAM_REPO
+add_upstream_remote "$UPSTREAM_REPO"
 
 # Use a branch that is named for the release
 BRANCH_NAME="upgrade/$RELEASE_TAG"
@@ -109,28 +112,28 @@ BRANCH_NAME="upgrade/$RELEASE_TAG"
 # Check if the branch already exists on the origin
 # If it does, there is nothing more to do as the branch can be rebased from the MR
 if git show-branch "remotes/origin/$BRANCH_NAME" >/dev/null 2>&1; then
-	echo "[INFO] Merge branch already created for $RELEASE_TAG"
-	exit
+  echo "[INFO] Merge branch already created for $RELEASE_TAG"
+  exit
 fi
 
-merge_release_tag $RELEASE_TAG
+merge_release_tag "$RELEASE_TAG"
 
 # Check if the merge resulted in any changes being staged
 if [ -n "$(git status --short)" ]; then
-	echo "[INFO] Merge resulted in the following changes"
-	git status
+  echo "[INFO] Merge resulted in the following changes"
+  git status
 
-	# NOTE(scott): The GitHub create-pull-request action does
-	# the committing for us, so we only need to make branches
-	# and commits if running outside of GitHub actions.
-	if [ ! "$GITHUB_ACTIONS" ]; then
-		checkout_commmit_push $BRANCH_NAME $DEFAULT_BRANCH $RELEASE_TAG
-	fi
+  # NOTE(scott): The GitHub create-pull-request action does
+  # the committing for us, so we only need to make branches
+  # and commits if running outside of GitHub actions.
+  if [ ! "$GITHUB_ACTIONS" ]; then
+    checkout_commmit_push "$BRANCH_NAME" "$DEFAULT_BRANCH" "$RELEASE_TAG"
+  fi
 
-	# Write a file containing the branch name and tag
-	# for automatic PR or MR creation that follows
-	echo "BRANCH_NAME=\"$BRANCH_NAME\"" >.mergeenv
-	echo "RELEASE_TAG=\"$RELEASE_TAG\"" >>.mergeenv
+  # Write a file containing the branch name and tag
+  # for automatic PR or MR creation that follows
+  echo "BRANCH_NAME=\"$BRANCH_NAME\"" >.mergeenv
+  echo "RELEASE_TAG=\"$RELEASE_TAG\"" >>.mergeenv
 else
-	echo "[INFO] Merge resulted in no changes"
+  echo "[INFO] Merge resulted in no changes"
 fi
