Send errors to stderr

diff --git a/bin/ensure-venv b/bin/ensure-venv
--- a/bin/ensure-venv
+++ b/bin/ensure-venv
@@ -7,7 +7,7 @@
 # NOTE: Python 3.8 or newer is required for ansible 2.12 
 # which is in turn required for the 'undef' ansible keyword
 PY_MAJOR=3
-PY_MINOR=8
+PY_MINOR=10
 version_check() {
 cat << EOF | python3
 import sys
@@ -17,8 +17,8 @@ EOF
 }
 
 if ! version_check; then
-  echo "Minimum required python version is $PY_MAJOR.$PY_MINOR"
-  echo "Please install a supported version then try again"
+  echo "Minimum required python version is $PY_MAJOR.$PY_MINOR" 1>&2
+  echo "Please install a supported version then try again" 1>&2
   exit 1
 fi
 
