Add specific support for Swift backend

diff --git a/bin/seed-ssh b/bin/seed-ssh
--- a/bin/seed-ssh
+++ b/bin/seed-ssh
@@ -20,10 +20,21 @@ if [ "$AZIMUTH_TERRAFORM_BACKEND_TYPE" = "local" ]; then
 else
     # If the Terraform backend type is something other than local, make a terraform
     # directory containing a backend configuration that specifies the type
-    # The rest of the configuration should come from environment variables
-    terraform_dir="$AZIMUTH_CONFIG_ROOT/.work/terraform"
+    # We support some special cases where additional environment variables are respected
+    # In other cases, the backend configuration should come from environment variables
+    terraform_dir="$AZIMUTH_CONFIG_ROOT/.work/seed-ssh"
     mkdir -p "$terraform_dir"
-    echo -e "terraform {\n  backend \"${AZIMUTH_TERRAFORM_BACKEND_TYPE}\" {}\n}" > "$terraform_dir/backend.tf"
+    echo "terraform {" > "$terraform_dir/backend.tf"
+    echo "  backend \"${AZIMUTH_TERRAFORM_BACKEND_TYPE}\" {" >> "$terraform_dir/backend.tf"
+    if [ "$AZIMUTH_TERRAFORM_BACKEND_TYPE" = "swift" ]; then
+        if [ -z "$AZIMUTH_TERRAFORM_BACKEND_SWIFT_CONTAINER" ]; then
+            echo "AZIMUTH_TERRAFORM_BACKEND_SWIFT_CONTAINER is required for the Swift backend" >&2
+            exit 1
+        fi
+        echo "    container = \"${AZIMUTH_TERRAFORM_BACKEND_SWIFT_CONTAINER}\"" >> "$terraform_dir/backend.tf"
+    fi
+    echo "  }" >> "$terraform_dir/backend.tf"
+    echo "}" >> "$terraform_dir/backend.tf"
     terraform -chdir="$terraform_dir" init
 fi
 
